from enum import Enum


class DealStatus(str, Enum):
    CREATED = "CREATED"
    WAITING_FOR_AGREEMENT = "WAITING_FOR_AGREEMENT"
    AGREED = "AGREED"
    ESCROW_CREATING = "ESCROW_CREATING"
    WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT"
    PAYMENT_DETECTED = "PAYMENT_DETECTED"
    FUNDED = "FUNDED"
    DELIVERING = "DELIVERING"
    DELIVERED = "DELIVERED"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"
    COMPLETED = "COMPLETED"
    DISPUTED = "DISPUTED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class TransactionType(str, Enum):
    DEPOSIT = "DEPOSIT"
    PAYOUT = "PAYOUT"
    REFUND = "REFUND"


class TransactionStatus(str, Enum):
    DETECTED = "DETECTED"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
